// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Rxdb$Reasonbot = require("./Rxdb.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var dbName = "./reasonbot";

var DBError = Caml_exceptions.create("Db-Reasonbot.DBError");

Pervasives.print_string("Trying to connect to DB: ./reasonbot");

var db = Rxdb$Reasonbot.create(dbName).then((function (v) {
          Pervasives.print_string("Successfully connected to DB.");
          return Promise.resolve(v);
        })).catch((function (err) {
        console.log("Failed to connect to DB: ./reasonbot", err);
        throw [
              DBError,
              err
            ];
      }));

exports.dbName = dbName;
exports.DBError = DBError;
exports.db = db;
/*  Not a pure module */
