// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Bot$Reasonbot = require("../src/Bot.bs.js");
var TestHelper$Reasonbot = require("./TestHelper.bs.js");

TestHelper$Reasonbot.test("token is not empty", (function () {
        return TestHelper$Reasonbot.toBe(0, TestHelper$Reasonbot.not_(TestHelper$Reasonbot.expect(Bot$Reasonbot.token.length)));
      }));

TestHelper$Reasonbot.testAsync(/* None */0, "bot constructs successfully", (function (cb) {
        Bot$Reasonbot.createBot(/* None */0, (function () {
                return Curry._1(cb, TestHelper$Reasonbot.pass);
              }));
        return /* () */0;
      }));

/*  Not a pure module */
